image: node:10.15-alpine

include:
  # See template for docs
  # https://gitlab.unueng.com/gitlab-ci/templates/tree/master/npm/
  - project: 'gitlab-ci/templates'
    # We use master instead of branches so we can automatically roll out updates
    # That are not breaking changes. We do versioning on a file level
    # If these break a user can manually go back and update the ref tag to a previous commit
    ref: master
    file: '/npm/0.1-template.yml'

variables:
  # Configure the rabbitmq server
  RABBITMQ_DEFAULT_USER: "guest"
  RABBITMQ_DEFAULT_PASS: "guest"

services:
  - rabbitmq:3.8-management-alpine
