image: node:14.19-alpine

include:
  # See template for docs
  # https://gitlab.unueng.com/gitlab-ci/templates/tree/master/npm/
  - project: 'gitlab-ci/templates'
    # We use master instead of branches so we can automatically roll out updates
    # That are not breaking changes. We do versioning on a file level
    # If these break a user can manually go back and update the ref tag to a previous commit
    ref: master
    file: '/npm/0.2-template.yml'

variables:
  # Configure the rabbitmq server
  RABBITMQ_DEFAULT_USER: "guest"
  RABBITMQ_DEFAULT_PASS: "guest"
  ESLINT_CODE_QUALITY_REPORT: gl-codequality.json

services:
  - r.unueng.com/cloud/taube/rabbitmq-mqtt:3.9

test-node16-14:
  image: node:16.14-alpine
  stage: test
  script:
  - npm i
  - npm run test

test-pact:
  image: node:14.19
  stage: test
  script:
  - npm i
  - npm run test-pact

audit:
  stage: test
  script:
  - npm audit --registry https://registry.npmjs.org/ --production
  cache:
    policy: pull
    paths:
    - node_modules/
  allow_failure: true

# override from template to add code climate
lint:
  stage: test
  script:
  - npm run lint
  cache:
    policy: pull
    paths:
    - node_modules/
  artifacts:
    reports:
      codequality: gl-codequality.json

release docker image:
  image: r.unueng.com/infrastructure/gitlab-ci-helper:0.2
  stage: build
  before_script:
  - source /ci/helpers
  - docker_login
  - echo "${NPMRC}" > .npmrc
  cache: {} # Remove cache else it gets added to docker image
  script:
  - docker_optional_image_name rabbitmq-mqtt
  - docker_build -f rabbitmq-mqtt.dockerfile
  - docker_release_latest
  - docker_release_tag 3.9
  when: manual
