image: node:18.13-alpine

stages:
- build
- test
- release

before_script:
- echo "@cloud:registry=https://gitlab.unueng.com/api/v4/packages/npm/" > ~/.npmrc
- echo "@infrastructure:registry=https://gitlab.unueng.com/api/v4/packages/npm/" >> ~/.npmrc
- echo "@cas:registry=https://gitlab.unueng.com/api/v4/packages/npm/" >> ~/.npmrc
- echo "//${CI_SERVER_HOST}/api/v4/packages/npm/:_authToken=${CI_JOB_TOKEN}" >> ~/.npmrc
- echo "//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}" >> ~/.npmrc
# Give access to write to the public NPM repo
- echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> ~/.npmrc

variables:
  # Configure the rabbitmq server
  RABBITMQ_DEFAULT_USER: "guest"
  RABBITMQ_DEFAULT_PASS: "guest"
  ESLINT_CODE_QUALITY_REPORT: gl-codequality.json

services:
  - r.unueng.com/cloud/rabbitmq-plugins:3.9-1

setup:
  stage: build
  script:
  - npm install
  cache:
    policy: pull-push
    paths:
    - node_modules/

# Overwrite the template test job, so we can wait for rabbitmq to be running
# Moving this to the tests did not work as expected and tests kept still failing
test:
  stage: test
  script:
  # Wait for RabbitMQ to be running
  - while ! nc -z localhost 15692 ; do sleep 1 ; done
  - npm run test
  - npm run test-coverage
  cache:
    policy: pull
    paths:
    - node_modules/
  coverage: '/Statements.*?(\d+(?:\.\d+)?)%/'
  artifacts:
    reports:
      junit: results.xml

# override from template to add code climate
lint:
  stage: test
  script:
  - npm run lint
  cache:
    policy: pull
    paths:
    - node_modules/
  artifacts:
    reports:
      codequality: gl-codequality.json

audit:
  stage: test
  script:
  - npm audit --registry https://registry.npmjs.org/ --production
  cache:
    policy: pull
    paths:
    - node_modules/
  allow_failure: true

publish:
  stage: release
  script: npm publish --access public
  only:
    refs:
    - tags
